### ISSUE TITLE
Error while installing adobe/reactor

### ISSUE THREAD

**Issue by devopsfactory-in** [adobe/reactor-sdk-javascript#12]
Hi Team,

While executing the 'npm install @adobe/reactor-sdk --save'  we are getting the following error.
If we change the name in package.json then it executed normally. Is this a know issue?
---------------------------------------------------
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@adobe/reactor-sdk" under a package
npm ERR! also called "@adobe/reactor-sdk". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by perlmonger42** [comment]
If you want to use the `@adobe/reactor-sdk` library as an include in your own project, then your own project should have a different name -- because you're developing your own `MysteriousMasterBrakeCylinder` application (as a silly example), not the `@adobe/reactor-sdk` library. 

I.e., _your_ `package.json` should have _your_ project's name (e.g. `MysteriousMasterBrakeCylinder`), which should be different from `@adobe/reactor-sdk`, because that would be a name collision with the `@adobe/reactor-sdk` library that your project is using.

That seems to be how you've resolved the problem, and if you're developing code that _uses_ `@adobe/reactor-sdk`, that's the correct course of action.

If, on the other hand, you're wanting to hack on `@adobe/reactor-sdk` itself, then you should follow the README instructions in the **Developer Setup** section (i.e., `git clone git@github.com:Adobe-Marketing-Cloud/reactor-sdk-javascript.git`, etc.), rather than the **Installation** section (i.e., the `npm install @adobe/reactor-sdk --save` that you're having trouble with). In that case, you won't have a collision between project names, because there's only the one project involved (`@adobe/reactor-sdk`), _and_ you're not even using the tool that generated the error (`npm install...`).
